# Generated by Django 3.0 on 2022-01-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_block', models.CharField(help_text='Name of the field block', max_length=100, verbose_name='Field Block Name')),
                ('text_data', models.TextField(help_text='Text Data for the field with HTML paragraph config', verbose_name='Text Data')),
                ('file_path', models.FileField(upload_to='', verbose_name='Path to HTML')),
                ('url_link', models.URLField(help_text='URL clickable link to AI/ML projects', verbose_name='Link to project')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
