# Generated by Django 3.0 on 2022-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio_landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Path to HTML'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='text_data',
            field=models.TextField(blank=True, help_text='Text Data for the field with HTML paragraph config', null=True, verbose_name='Text Data'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url_link',
            field=models.URLField(blank=True, help_text='URL clickable link to AI/ML projects', null=True, verbose_name='Link to project'),
        ),
    ]
